window.outdoorSpots = [
  {
    slug: "la-jolla",
    sport: "dive",
    sportLabel: "DIVE",
    regionGroup: "California",
    href: "la-jolla.html",
    city: "San Diego",
    name: "Scripps Beach",
    grade: "C",
    gradeClass: "grade-c",
    primaryText: "10-14 ft",
    fill: 59,
    image: "camera-snapshots/san-diego.png?v=20260618-0357",
    imageAlt: "Scripps Pier underwater visibility camera preview",
    imageLabel: "Daily camera frame",
    metrics: [
      ["Visibility", "10-14 ft"],
      ["Water", "69.8 F"],
      ["Wind", "11.0 mph"],
      ["Window", "Morning"],
    ],
  },
  {
    slug: "lower-keys",
    sport: "dive",
    sportLabel: "DIVE",
    regionGroup: "Florida",
    href: "lower-keys.html",
    city: "Lower Keys, Florida",
    name: "Viva The Keys Reef",
    grade: "B",
    gradeClass: "grade-b",
    primaryText: "15-25 ft",
    fill: 70,
    image: "camera-snapshots/lower-keys.jpg?v=20260619-1802",
    imageAlt: "Lower Keys underwater camera snapshot",
    imageLabel: "Daily camera frame",
    metrics: [
      ["Visibility", "15-25 ft"],
      ["Water", "80.6 F"],
      ["Wind", "8.2 mph"],
      ["Window", "Morning"],
    ],
  },
  {
    slug: "deerfield-beach",
    sport: "dive",
    sportLabel: "DIVE",
    regionGroup: "Florida",
    href: "deerfield-beach.html",
    city: "Deerfield Beach, Florida",
    name: "International Fishing Pier",
    grade: "C",
    gradeClass: "grade-c",
    primaryText: "10-18 ft",
    fill: 58,
    image: "camera-snapshots/deerfield-beach.jpg?v=20260619-1802",
    imageAlt: "Deerfield Beach underwater camera snapshot",
    imageLabel: "Daily camera frame",
    metrics: [
      ["Visibility", "10-18 ft"],
      ["Water", "79.2 F"],
      ["Wind", "10.4 mph"],
      ["Window", "Early calm"],
    ],
  },
  {
    slug: "utopia-sandy-channel",
    sport: "dive",
    sportLabel: "DIVE",
    regionGroup: "Caribbean",
    href: "utopia-sandy-channel.html",
    city: "Roatan",
    name: "Utopia Village Sandy Channel",
    grade: "A",
    gradeClass: "grade-a",
    primaryText: "25-35 ft",
    fill: 84,
    image: "camera-snapshots/utopia-sandy-channel.jpg?v=20260619-1802",
    imageAlt: "Utopia Village Sandy Channel camera snapshot",
    imageLabel: "Daily camera frame",
    metrics: [
      ["Visibility", "25-35 ft"],
      ["Water", "82.1 F"],
      ["Wind", "6.0 mph"],
      ["Window", "Most of day"],
    ],
  },
  {
    slug: "utopia-reef-cam",
    sport: "dive",
    sportLabel: "DIVE",
    regionGroup: "Caribbean",
    href: "utopia-reef-cam.html",
    city: "Roatan",
    name: "Utopia Village Reef Cam",
    grade: "A",
    gradeClass: "grade-a",
    primaryText: "25-35 ft",
    fill: 86,
    image: "camera-snapshots/utopia-reef-cam.jpg?v=20260619-1802",
    imageAlt: "Utopia Village reef camera snapshot",
    imageLabel: "Daily camera frame",
    metrics: [
      ["Visibility", "25-35 ft"],
      ["Water", "82.4 F"],
      ["Wind", "5.8 mph"],
      ["Window", "Now-afternoon"],
    ],
  },
  {
    slug: "catalina-wrigley",
    sport: "dive",
    sportLabel: "DIVE",
    regionGroup: "California",
    href: "catalina-wrigley.html",
    city: "Catalina Island",
    name: "Wrigley Catalina Marine Reserve",
    grade: "B",
    gradeClass: "grade-b",
    primaryText: "15-25 ft",
    fill: 72,
    image: "camera-snapshots/catalina-wrigley.jpg?v=20260619-1802",
    imageAlt: "USC Wrigley Catalina Marine Reserve camera snapshot",
    imageLabel: "Daily camera frame",
    metrics: [
      ["Visibility", "15-25 ft"],
      ["Water", "65.8 F"],
      ["Wind", "9.4 mph"],
      ["Window", "Morning"],
    ],
  },
  {
    slug: "anacapa-ocean",
    sport: "dive",
    sportLabel: "DIVE",
    regionGroup: "California",
    href: "anacapa-ocean.html",
    city: "Channel Islands",
    name: "Anacapa Ocean",
    grade: "C",
    gradeClass: "grade-c",
    primaryText: "10-20 ft",
    fill: 61,
    image: "camera-snapshots/anacapa-ocean.jpg?v=20260619-1802",
    imageAlt: "Anacapa Ocean underwater camera snapshot",
    imageLabel: "Daily camera frame",
    metrics: [
      ["Visibility", "10-20 ft"],
      ["Water", "63.4 F"],
      ["Wind", "11.0 mph"],
      ["Window", "Protected side"],
    ],
  },
  {
    slug: "coral-city",
    sport: "dive",
    sportLabel: "DIVE",
    regionGroup: "Florida",
    href: "coral-city.html",
    city: "Miami",
    name: "Coral City Camera",
    grade: "B",
    gradeClass: "grade-b",
    primaryText: "15-25 ft",
    fill: 74,
    image: "camera-snapshots/coral-city.jpg?v=20260619-1802",
    imageAlt: "Coral City Camera reef snapshot",
    imageLabel: "Daily camera frame",
    metrics: [
      ["Visibility", "15-25 ft"],
      ["Water", "81.0 F"],
      ["Wind", "7.4 mph"],
      ["Window", "Midday"],
    ],
  },
  {
    slug: "pompano-pier",
    sport: "dive",
    sportLabel: "DIVE",
    regionGroup: "Florida",
    href: "pompano-pier.html",
    city: "Pompano Beach",
    name: "Underwater Pier Cam",
    grade: "C",
    gradeClass: "grade-c",
    primaryText: "10-18 ft",
    fill: 59,
    image: "camera-snapshots/pompano-pier.jpg?v=20260619-1802",
    imageAlt: "Pompano Beach underwater pier camera snapshot",
    imageLabel: "Daily camera frame",
    metrics: [
      ["Visibility", "10-18 ft"],
      ["Water", "79.0 F"],
      ["Wind", "9.0 mph"],
      ["Window", "Before wind"],
    ],
  },
];
